//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageGame
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public double PositionX { get; set; }
        public double PositionY { get; set; }
        public int Round { get; set; }
        public int ImageCate { get; set; }
        public int IdPuzzleGame { get; set; }
    
        public virtual Puzzle Puzzle { get; set; }
    }
}
