//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleGame.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PuzzleGameEntities : DbContext
    {
        public PuzzleGameEntities()
            : base("name=PuzzleGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImageGame> ImageGames { get; set; }
        public virtual DbSet<MediaGame> MediaGames { get; set; }
        public virtual DbSet<Puzzle> Puzzles { get; set; }
    }
}
